// webhook.js — Full AI-powered version (Gemini handles intent + human-like responses)
// Changes from previous version:
//   1. Gemini now generates ALL bot responses — no more hardcoded text
//   2. Bot speaks natural Tagalog/Taglish/English like a real receptionist
//   3. State machine still controls the booking flow (safety net)
//   4. Gemini knows the current state so replies are always contextually correct
//   5. Structured data (slots, booking summary) still generated by code, but Gemini wraps them warmly

const express = require("express");
const axios = require("axios");
const { createClient } = require("@supabase/supabase-js");

// --- IMPORT MENU COMPONENTS (unchanged) ---
const sendIntroMenu = require('./menu/sendIntroMenu');
const sendAppointmentForButtonTemplate = require('./menu/sendAppointmentForButtonTemplate');
const sendTimeSlotButtonTemplate = require('./menu/sendTimeSlotButtonTemplate');
const sendConfirmationButtonTemplate = require('./menu/sendConfirmationButtonTemplate');
const sendBookingPromptButtonTemplate = require('./menu/sendBookingPromptButtonTemplate');
const sendUnknownInputCard = require('./menu/sendUnknownInputCard');

const router = express.Router();

const VERIFY_TOKEN = "palodentcare_secret_token";

// --- Supabase Client ---
if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_KEY) {
  console.error("❌ Missing SUPABASE_URL or SUPABASE_SERVICE_KEY environment variables.");
}
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

// ---------------------------------------------------------------------------
// GEMINI — FULL AI RECEPTIONIST
// Handles BOTH intent detection AND generating human-like responses
// ---------------------------------------------------------------------------

const userConversationHistory = {};
const intentHistoryTimestamps = {};

// This is the heart of the AI receptionist.
// Gemini knows the clinic, the current state, and responds like a warm Filipino receptionist.
const GEMINI_SYSTEM_PROMPT = `Ikaw si "Ate Claire", ang friendly at mainit na receptionist ng Palo Dentcare dental clinic sa Pilipinas. 
Nagsasalita ka ng natural na Taglish (mixed Tagalog at English), at minsan Bisaya kung naririnig mo ito sa patient.

Ang trabaho mo:
1. Intindihin ang mensahe ng patient
2. I-detect ang kanyang intent
3. Mag-generate ng natural, warm, human-like na reply

CLINIC INFO:
- Pangalan: Palo Dentcare
- Bukas: Lunes hanggang Sabado, 9:00 AM - 6:00 PM
- Sarado: Linggo
- Lunch break: 12:00 PM - 1:00 PM (walang booking)
- Appointment slots: bawat 20 minuto

INTENTS na kailangan mong i-detect:
- "greet"               → nagbabati ang patient
- "book_appointment"    → gusto mag-book ng appointment
- "cancel_appointment"  → gusto i-cancel ang appointment
- "confirm_appointment" → gusto i-confirm ang appointment gamit ang code
- "cancel_flow"         → gusto huminto / mag-exit sa kasalukuyang proseso
- "gratitude"           → nagpapasalamat ang patient
- "yes"                 → pumapayag / nagko-confirm
- "no"                  → tumututol / nagde-decline
- "unknown"             → hindi malinaw ang mensahe

PERSONALITY:
- Warm, maalalahanin, at propesyonal
- Gumagamit ng "po" at "opo" nang natural
- Gumagamit ng emojis nang paminsan-minsan 😊🦷
- Maikli at malinaw ang mga sagot — hindi masyadong mahaba
- Parang tunay na receptionist, hindi robot
- Kung minsan nagbibigay ng encouraging na salita

CURRENT STATE na ipapasa sa iyo:
Bago ka mag-reply, may "state" na ipapadala sa iyo para malaman mo kung saan na sa proseso ang patient.
Gamitin ito para ang reply mo ay laging angkop sa sitwasyon.

STATES at kung paano ka dapat mag-respond:
- "default"                    → Tanggapin ang kanyang mensahe at tulungan siya
- "awaiting_date"              → Hintayin ang date sa format YYYY-MM-DD
- "awaiting_slot"              → Pinipili ng patient ang time slot
- "awaiting_my_name"           → Hihingin ang pangalan ng patient
- "awaiting_my_phone"          → Hihingin ang phone number (o skip)
- "awaiting_patient_name"      → Hihingin ang pangalan ng taong ibo-book
- "awaiting_patient_phone"     → Hihingin ang phone number ng taong ibo-book
- "awaiting_my_confirm_match"  → Nag-ask kung siya ba yung nakitang record (YES/NO)
- "awaiting_for_whom"          → Nag-ask kung para kanino ang booking
- "awaiting_confirm_code"      → Hintayin ang appointment code para i-confirm
- "awaiting_cancel_code"       → Hintayin ang appointment code para i-cancel
- "awaiting_cancel_code_retry" → Nagkamali ng code, try again o cancel
- "awaiting_booking_prompt_response" → Nag-ask kung gusto pang mag-book
- "confirming"                 → Nag-show ng booking summary, waiting for confirm/cancel
- "awaiting_unknown_confirm"   → Hindi naintindihan ang mensahe

RULES:
- Laging mag-return ng PURE JSON — walang markdown, walang backticks, walang extra text
- Ang "reply" field ay ang mensahe na makikita ng patient sa Messenger
- Huwag mag-include ng booking details sa reply — hawak ng code ang structured data
- Kung may state na "awaiting_date", palaging i-remind ang format: YYYY-MM-DD
- Kung may state na "awaiting_slot", sabihin na mag-tap ng button
- Kung may state na "confirming", hintayin ang kanilang confirmation

JSON FORMAT — return ONLY this, nothing else:
{
  "intent": "<intent>",
  "confidence": <0.0-1.0>,
  "reply": "<natural Taglish reply na makikita ng patient>"
}

EXAMPLES ng magandang replies:
- Greeting: "Magandang araw po! 😊 Welcome sa Palo Dentcare! Paano kita matutulungan ngayon? Pwede kayong mag-book ng appointment, i-confirm, o i-cancel. 🦷"
- Book: "Sige po! Para makapag-book kayo ng appointment, pakitype lang ang inyong preferred na petsa sa format na YYYY-MM-DD (halimbawa: 2025-12-20). 😊"
- Cancel flow: "Okay lang po! Kung kailangan ninyo ng tulong sa ibang pagkakataon, nandito lang kami. Ingat po! 😊"
- Gratitude: "Salamat din po! God bless kayo! 🙏 Kung may katanungan kayo, huwag mag-alinlangang mag-message ulit. 😊"
- Unknown: "Pasensya na po, hindi ko po nagets ang inyong mensahe. 😅 Pwede ba kayong ulitin o pumili mula sa menu?"
- Confirm yes: "Naku, salamat po sa pagko-confirm! ✅ Makakakita na kayo ng reminder bago ang inyong appointment. Ingat po! 🦷"
- Cancel: "Naiintindihan ko po. Na-cancel na ang inyong appointment. Kung gusto ninyong mag-book ulit, sabihin lang po! 😊"
- Awaiting name: "Pakitype lang po ang inyong buong pangalan para sa appointment. 😊"
- Awaiting phone: "May contact number po ba kayo? Pwede ring mag-type ng 'skip' kung ayaw ninyong ibigay. 📱"
- Date invalid: "Hmm, parang hindi po tama ang format ng petsa. 😊 Pakitype ulit sa format na YYYY-MM-DD, halimbawa: 2025-12-20."
- Sunday: "Pasensya na po, sarado kami tuwing Linggo. 😊 Pwede po kayong pumili ng ibang araw — Lunes hanggang Sabado lang po kami bukas!"
- Past date: "Ay, nakaraan na po ang petsang iyon! 😅 Pakitype ng petsa na hindi pa nakaraan po."
- No slots: "Pasensya na po, puno na ang slots para sa araw na iyon. 😔 Pwede po kayong pumili ng ibang petsa?"
- Double booking: "Mukhang may appointment na kayo sa petsang iyon! 😊 Gusto ninyo pong mag-book para sa ibang tao, o pumili ng ibang petsa para sa inyo?"`;

async function getGeminiResponse(message, sender_psid, currentState, extraContext = "") {
  const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
  if (!GEMINI_API_KEY) {
    console.error("❌ Missing GEMINI_API_KEY environment variable.");
    return { intent: "unknown", confidence: 0, reply: "Sorry, may technical issue kami ngayon. Pakisubukan ulit mamaya." };
  }

  if (!userConversationHistory[sender_psid]) {
    userConversationHistory[sender_psid] = [];
  }

  const contextualMessage = `[CURRENT STATE: ${currentState}${extraContext ? ` | CONTEXT: ${extraContext}` : ""}]
Patient message: ${message}`;

  userConversationHistory[sender_psid].push({
    role: "user",
    parts: [{ text: contextualMessage }]
  });

  const history = userConversationHistory[sender_psid].slice(-10);

  try {
    // Updated to gemini-2.5-flash — 2.0-flash deprecated March 2026
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`;

    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        system_instruction: {
          parts: [{ text: GEMINI_SYSTEM_PROMPT }]
        },
        contents: history,
        generationConfig: {
          temperature: 0.4,
          maxOutputTokens: 400,
          responseMimeType: "application/json"  // forces Gemini to always return valid JSON
        }
      })
    });

    const data = await response.json();

    if (data.error) {
      console.error("❌ Gemini API error:", data.error);
      return { intent: "unknown", confidence: 0, reply: "Sorry po, may technical issue kami. Pakisubukan ulit." };
    }

    const raw = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "{}";

    // Robust JSON parsing with multiple fallback strategies
    let parsed = { intent: "unknown", confidence: 0, reply: null };
    try {
      // Step 1: strip markdown fences
      let clean = raw.replace(/```json|```/g, "").trim();

      // Step 2: extract JSON object if there's extra text around it
      const jsonMatch = clean.match(/{[sS]*}/);
      if (jsonMatch) clean = jsonMatch[0];

      // Step 3: remove unescaped newlines inside strings
      clean = clean.replace(/[
]+/g, " ");

      parsed = JSON.parse(clean);
    } catch (parseErr) {
      console.error("❌ JSON parse failed, using regex fallback:", parseErr.message);

      // Step 4: extract fields individually — handles partially malformed JSON
      const intentMatch = raw.match(/"intent"s*:s*"([^"]+)"/);
      const replyMatch = raw.match(/"reply"s*:s*"([sS]*?)(?:"|$)/);
      const confidenceMatch = raw.match(/"confidence"s*:s*([d.]+)/);

      parsed = {
        intent: intentMatch?.[1] || "unknown",
        confidence: confidenceMatch ? parseFloat(confidenceMatch[1]) : 0.5,
        reply: replyMatch?.[1]?.replace(/\n/g, "
") || null
      };
      console.log(`[GEMINI FALLBACK] intent="${parsed.intent}" reply="${parsed.reply?.substring(0, 40)}"`);
    }

    // Store reply in history
    userConversationHistory[sender_psid].push({
      role: "model",
      parts: [{ text: raw }]
    });

    console.log(`[GEMINI] state="${currentState}" intent="${parsed.intent}" reply="${parsed.reply?.substring(0, 60)}..."`);
    return parsed;

  } catch (err) {
    console.error("❌ getGeminiResponse error:", err.message);
    return { intent: "unknown", confidence: 0, reply: "Sorry po, may nangyari. Pakisubukan ulit." };
  }
}

// Cleanup old histories every 30 minutes
setInterval(() => {
  const now = Date.now();
  for (const psid of Object.keys(intentHistoryTimestamps)) {
    if (now - intentHistoryTimestamps[psid] > 60 * 60 * 1000) {
      delete userConversationHistory[psid];
      delete intentHistoryTimestamps[psid];
      console.log(`[CLEANUP] Removed history for ${psid}`);
    }
  }
}, 30 * 60 * 1000);

// ---------------------------------------------------------------------------
// END GEMINI AI RECEPTIONIST
// ---------------------------------------------------------------------------

// --- Helper: emit full appointment row ---
async function emitAppointmentUpdate(io, clinicId, appointmentId) {
  try {
    if (!io || !clinicId || !appointmentId) return;
    const { data: appt, error } = await supabase
      .from('appointments')
      .select('*')
      .eq('clinic_id', clinicId)
      .eq('id', appointmentId)
      .maybeSingle();
    if (error || !appt) return;
    io.emit("appointment-updated", appt);
  } catch (err) {
    console.error("emitAppointmentUpdate error:", err);
  }
}

// --- Clinic lookup by Messenger Page ID ---
async function getClinicByMessengerPageId(pageId) {
  const { data, error } = await supabase
    .from('clinics')
    .select('*')
    .eq('messenger_page_id', pageId)
    .maybeSingle();
  if (error) {
    console.error("Supabase clinic lookup error:", error);
    return null;
  }
  return data || null;
}

// --- Conversation state ---
let userStates = {};
let justCancelled = {};

function normalize(str) {
  return str.toLowerCase().replace(/[^\w ]/g, '').trim();
}

function toTitleCase(str) {
  return str.replace(/\b\w+/g, txt => txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase());
}

function to12HourFormat(time24) {
  const [hourStr, minStr] = time24.split(':');
  let hour = parseInt(hourStr, 10);
  const min = minStr;
  const ampm = hour >= 12 ? 'PM' : 'AM';
  hour = hour % 12 || 12;
  return `${hour.toString().padStart(2, '0')}:${min} ${ampm}`;
}

function to24HourFormat(time12) {
  let [time, ampm] = time12.split(' ');
  let [h, m] = time.split(':');
  h = parseInt(h, 10);
  if (ampm === 'PM' && h < 12) h += 12;
  if (ampm === 'AM' && h === 12) h = 0;
  return `${h.toString().padStart(2, '0')}:${m}`;
}

// Messenger send
async function sendMessage(sender_psid, response, pageAccessToken) {
  if (!pageAccessToken) {
    console.error("❌ Missing pageAccessToken.");
    return;
  }
  try {
    await axios.post(
      `https://graph.facebook.com/v17.0/me/messages?access_token=${pageAccessToken}`,
      { recipient: { id: sender_psid }, message: { text: response } }
    );
  } catch (err) {
    console.error("❌ Error sending message:", err.response?.data || err.message);
  }
}

// --- Active dentists ---
async function getActiveDentists(clinicId) {
  let query = supabase
    .from('dentists')
    .select('id,name')
    .eq('is_active', true)
    .order('name', { ascending: true });
  if (clinicId) query = query.eq('clinic_id', clinicId);
  const { data, error } = await query;
  if (error) { console.error("getActiveDentists error:", error); return []; }
  return data || [];
}

// --- Find patient by messenger_id ---
async function findPatientByMessengerId(messenger_id, clinicId) {
  let query = supabase.from('patients').select('*').eq('messenger_id', messenger_id);
  if (clinicId) query = query.eq('clinic_id', clinicId);
  const { data, error } = await query.maybeSingle();
  if (error) { console.error("findPatientByMessengerId error:", error); return null; }
  return data || null;
}

// --- Find patient by name & phone ---
async function findPatientByNameAndPhone(name, phone, clinicId) {
  if (phone) {
    let q = supabase.from('patients').select('*').eq('phone', phone).ilike('name', name).limit(1);
    if (clinicId) q = q.eq('clinic_id', clinicId);
    const { data, error } = await q;
    if (!error && data && data.length > 0) return data[0];
  }
  let q2 = supabase.from('patients').select('*').ilike('name', name).limit(1);
  if (clinicId) q2 = q2.eq('clinic_id', clinicId);
  const { data: data2, error: error2 } = await q2;
  if (error2) { console.error("findPatientByNameAndPhone error:", error2); return null; }
  return (data2 && data2.length > 0) ? data2[0] : null;
}

function generateTimeSlots(start = "09:00", end = "18:00", interval = 20) {
  const slots = [];
  let [hour, minute] = start.split(":").map(Number);
  const [endHour, endMinute] = end.split(":").map(Number);
  while (hour < endHour || (hour === endHour && minute < endMinute)) {
    const slot = `${hour.toString().padStart(2, "0")}:${minute.toString().padStart(2, "0")}`;
    slots.push(slot);
    minute += interval;
    if (minute >= 60) { hour += 1; minute = minute % 60; }
  }
  return slots.filter(slot => !["12:00", "12:20", "12:40"].includes(slot));
}

function isClinicOpen(dateStr) {
  return new Date(dateStr).getDay() !== 0;
}

async function getBookedSlotCountsForActiveDentists(activeDentists, dateStr, clinicId) {
  const slotCounts = {};
  if (!activeDentists.length) return slotCounts;
  const dentistIds = activeDentists.map(d => d.id);
  const startISO = `${dateStr}T00:00:00+08:00`;
  const endISO = `${dateStr}T23:59:59+08:00`;
  let query = supabase.from('appointments').select('dentist_id, appointment_time, status')
    .in('dentist_id', dentistIds).gte('appointment_time', startISO).lte('appointment_time', endISO);
  if (clinicId) query = query.eq('clinic_id', clinicId);
  const { data, error } = await query;
  if (error) { console.error("getBookedSlotCounts error:", error); return slotCounts; }
  (data || []).forEach(appt => {
    if (appt.status === 'Cancelled') return;
    const time = new Date(appt.appointment_time);
    const slot = `${time.getHours().toString().padStart(2, '0')}:${time.getMinutes().toString().padStart(2, '0')}`;
    slotCounts[slot] = (slotCounts[slot] || 0) + 1;
  });
  return slotCounts;
}

async function computeSlotCapacities(activeDentists, dateStr, clinicId) {
  const baseSlots = generateTimeSlots("09:00", "18:00", 20);
  if (!activeDentists.length) return { baseSlots, capacity: {} };
  const capacity = {};
  baseSlots.forEach(s => { capacity[s] = activeDentists.length; });
  const dayOfWeek = new Date(dateStr).getDay();
  for (const dentist of activeDentists) {
    let q = supabase.from('dentist_availability').select('start_time,end_time,is_available')
      .eq('dentist_id', dentist.id).eq('is_available', false)
      .or(`specific_date.eq.${dateStr},day_of_week.eq.${dayOfWeek}`);
    if (clinicId) q = q.eq('clinic_id', clinicId);
    const { data, error } = await q;
    if (error) { console.error("computeSlotCapacities error:", error); continue; }
    (data || []).forEach(block => {
      const [startHour, startMin] = block.start_time.split(':').map(Number);
      const [endHour, endMin] = block.end_time.split(':').map(Number);
      baseSlots.forEach(slot => {
        const [h, m] = slot.split(':').map(Number);
        const slotMinutes = h * 60 + m;
        if (slotMinutes >= startHour * 60 + startMin && slotMinutes < endHour * 60 + endMin) {
          if (capacity[slot] > 0) capacity[slot] -= 1;
        }
      });
    });
  }
  return { baseSlots, capacity };
}

async function getAvailableSlots(dateStr, clinicId) {
  const activeDentists = await getActiveDentists(clinicId);
  if (!activeDentists.length) return { slots: [], activeDentists };
  const { baseSlots, capacity } = await computeSlotCapacities(activeDentists, dateStr, clinicId);
  const bookedSlotCounts = await getBookedSlotCountsForActiveDentists(activeDentists, dateStr, clinicId);
  let availableSlots = baseSlots.filter(slot => {
    const cap = capacity[slot] || 0;
    if (cap <= 0) return false;
    return (bookedSlotCounts[slot] || 0) < cap;
  }).map(to12HourFormat);
  const now = new Date();
  const bookingDate = new Date(dateStr);
  if (bookingDate.getFullYear() === now.getFullYear() &&
      bookingDate.getMonth() === now.getMonth() &&
      bookingDate.getDate() === now.getDate()) {
    availableSlots = availableSlots.filter(slot => {
      const slot24 = to24HourFormat(slot);
      const [h, m] = slot24.split(':').map(Number);
      const slotDate = new Date(dateStr);
      slotDate.setHours(h, m, 0, 0);
      return slotDate > now;
    });
  }
  return { slots: availableSlots, activeDentists };
}

async function hasDoubleBookingOnDate(patient_id, dateStr, clinicId) {
  const startISO = `${dateStr}T00:00:00+08:00`;
  const endISO = `${dateStr}T23:59:59+08:00`;
  let query = supabase.from('appointments').select('id,status')
    .eq('patient_id', patient_id).gte('appointment_time', startISO).lte('appointment_time', endISO);
  if (clinicId) query = query.eq('clinic_id', clinicId);
  const { data, error } = await query;
  if (error) { console.error("hasDoubleBookingOnDate error:", error); return false; }
  return (data || []).filter(a => a.status !== 'Cancelled').length > 0;
}

// --- WEBHOOK VERIFY ---
router.get("/webhook", (req, res) => {
  const mode = req.query["hub.mode"];
  const token = req.query["hub.verify_token"];
  const challenge = req.query["hub.challenge"];
  if (mode && token) {
    if (mode === "subscribe" && token === VERIFY_TOKEN) {
      console.log("✅ Webhook verified by Facebook");
      res.status(200).send(challenge);
    } else { res.sendStatus(403); }
  } else { res.sendStatus(400); }
});

// --- WEBHOOK EVENT HANDLER ---
router.post("/webhook", async (req, res) => {
  const body = req.body;
  if (body.object === "page") {
    for (const entry of body.entry) {
      const pageIdFromEntry = entry.id;
      for (const webhook_event of entry.messaging) {
        const sender_psid = webhook_event.sender?.id;
        if (webhook_event.delivery || webhook_event.read) continue;
        if (webhook_event.message?.is_echo) continue;
        const page_id = pageIdFromEntry || webhook_event.recipient?.id || webhook_event.sender?.id;
        const clinic = await getClinicByMessengerPageId(page_id);
        if (!clinic) { console.warn('[WARN] No clinic linked to page_id:', page_id); continue; }
        const clinicId = clinic.id;
        const pageAccessToken = clinic.fb_page_access_token;
        intentHistoryTimestamps[sender_psid] = Date.now();
        try {
          if (webhook_event.message?.text) {
            await handleMessage(sender_psid, webhook_event.message.text.trim(), webhook_event, req, clinicId, pageAccessToken);
          } else if (webhook_event.postback?.payload) {
            await handleMessage(sender_psid, webhook_event.postback.payload, webhook_event, req, clinicId, pageAccessToken);
          }
        } catch (err) {
          console.error('❌ Error in webhook handler:', err);
          await sendMessage(sender_psid, "Sorry po, may nangyari. Pakisubukan ulit. 😊", pageAccessToken);
        }
      }
    }
    return res.status(200).send("EVENT_RECEIVED");
  }
  res.sendStatus(404);
});

// ---------------------------------------------------------------------------
// MAIN LOGIC
// ---------------------------------------------------------------------------
async function handleMessage(sender_psid, message, webhook_event, req, clinicId, pageAccessToken) {
  console.log(`[DEBUG] state=${userStates[sender_psid]?.state} | message=${message}`);

  if (!userStates[sender_psid]) {
    userStates[sender_psid] = { state: "default", data: {} };
  }
  let userState = userStates[sender_psid];
  let normalizedMsg = normalize(message);

  // --- Postback buttons — handle directly, no Gemini needed ---
  // These are structured button taps, not free text

  if (message === 'UNKNOWN_INPUT_YES') {
    userStates[sender_psid] = { state: "default", data: {} };
    await sendIntroMenu(sender_psid, pageAccessToken);
    return;
  }
  if (message === 'UNKNOWN_INPUT_NO') {
    await sendMessage(sender_psid, "Sige po! Kung kailangan ninyo ng tulong, nandito lang kami. God bless! 😊", pageAccessToken);
    userStates[sender_psid] = { state: "default", data: {} };
    return;
  }
  if (message === 'MENU_BOOK_APPOINTMENT') {
    userState.state = "awaiting_date";
    await sendMessage(sender_psid, "Sige po! Pakitype ang inyong preferred na petsa sa format: YYYY-MM-DD (halimbawa: 2025-12-20) 😊", pageAccessToken);
    return;
  }
  if (message === 'MENU_CONFIRM_BOOKING') {
    userState.state = "awaiting_confirm_code";
    await sendMessage(sender_psid, "Pakitype po ang inyong appointment code (ID number) para ma-confirm namin. 😊", pageAccessToken);
    return;
  }
  if (message === 'MENU_CANCEL_APPOINTMENT') {
    userState.state = "awaiting_cancel_code";
    await sendMessage(sender_psid, "Pakitype po ang inyong appointment code (ID number) na gusto ninyong i-cancel.", pageAccessToken);
    return;
  }
  if (message === 'BOOK_ANOTHER_APPOINTMENT') {
    userStates[sender_psid] = { state: "awaiting_date", data: {} };
    await sendMessage(sender_psid, "Sige po! Pakitype ang bagong petsa sa format: YYYY-MM-DD 😊", pageAccessToken);
    return;
  }
  if (message === 'DECLINE_BOOKING') {
    await sendMessage(sender_psid, "Okay lang po! Kung kailangan ninyo ng appointment sa susunod, nandito lang kami. Ingat! 😊", pageAccessToken);
    userStates[sender_psid] = { state: "default", data: {} };
    return;
  }
  if (message === 'CONFIRM_BOOKING') normalizedMsg = 'confirm_booking';
  if (message === 'CANCEL_BOOKING') normalizedMsg = 'cancel_booking';

  // --- For all free-text messages, ask Gemini for intent + reply ---
  const isPostback = ['for_me', 'for_someone_else'].includes(message) ||
    message.startsWith('SLOT_') || message.startsWith('slot_');

  let geminiResult = { intent: "unknown", confidence: 0, reply: null };

  if (!isPostback && message !== 'CONFIRM_BOOKING' && message !== 'CANCEL_BOOKING') {
    try {
      geminiResult = await getGeminiResponse(message, sender_psid, userState.state);
    } catch (e) {
      console.error('[DEBUG] Gemini error:', e);
    }
  }

  const topIntent = geminiResult.intent || "unknown";
  const aiReply = geminiResult.reply;

  console.log(`[DEBUG] topIntent="${topIntent}" aiReply="${aiReply?.substring(0, 60)}"`);

  try {
    switch (userState.state) {

      case "default": {
        if (topIntent === 'greet') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          await sendIntroMenu(sender_psid, pageAccessToken);
          return;
        }
        if (topIntent === 'book_appointment') {
          userState.state = "awaiting_date";
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          return;
        }
        if (topIntent === 'cancel_appointment') {
          userState.state = "awaiting_cancel_code";
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          return;
        }
        if (topIntent === 'confirm_appointment') {
          userState.state = "awaiting_confirm_code";
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          return;
        }
        if (topIntent === 'gratitude') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          return;
        }
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        // Unknown — show decision card with AI reply first
        if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
        userStates[sender_psid].state = "awaiting_unknown_confirm";
        await sendUnknownInputCard(sender_psid, pageAccessToken);
        return;
      }

      case "awaiting_confirm_code": {
        // Global cancel check
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        const code = message.trim();
        if (!/^\d+$/.test(code)) {
          const reply = aiReply || "Hmm, parang hindi numero ang nitype ninyo. Pakitype po ang inyong appointment code (numbers only). 😊";
          await sendMessage(sender_psid, reply, pageAccessToken);
          return;
        }
        const { data: appointment, error: apptErr } = await supabase
          .from('appointments').select('*').eq('id', code).eq('clinic_id', clinicId).maybeSingle();
        if (apptErr || !appointment) {
          await sendMessage(sender_psid, "Ay, wala po kaming nahanap na appointment sa code na iyon. Pakicheck ulit ang inyong code. 😊", pageAccessToken);
          return;
        }
        const { data: patientRow } = await supabase.from('patients').select('messenger_id')
          .eq('id', appointment.patient_id).eq('clinic_id', clinicId).maybeSingle();
        if (!patientRow?.messenger_id) {
          const { data: existingPatient } = await supabase.from('patients').select('id')
            .eq('messenger_id', sender_psid).eq('clinic_id', clinicId).maybeSingle();
          if (existingPatient && existingPatient.id !== appointment.patient_id) {
            await supabase.from('appointments').update({ guardian_messenger_id: sender_psid })
              .eq('id', appointment.id).eq('clinic_id', clinicId);
          } else {
            await supabase.from('patients').update({ messenger_id: sender_psid })
              .eq('id', appointment.patient_id).eq('clinic_id', clinicId);
            await supabase.from('appointments').update({ guardian_messenger_id: null })
              .eq('id', appointment.id).eq('clinic_id', clinicId);
          }
        }
        if (["Completed", "Cancelled", "No Show"].includes(appointment.status)) {
          let statusMsg = "";
          if (appointment.status === "Completed") statusMsg = "Natapos na po ang appointment na ito. Gusto po ba ninyong mag-book ng bago? 😊";
          if (appointment.status === "Cancelled") statusMsg = "Na-cancel na po ang appointment na ito. Gusto po ba ninyong mag-book ng bago? 😊";
          if (appointment.status === "No Show") statusMsg = "Ang appointment na ito ay minarkahan bilang 'No Show'. Gusto po ba ninyong mag-book ng bago? 😊";
          await sendBookingPromptButtonTemplate(sender_psid, statusMsg, pageAccessToken);
          userStates[sender_psid] = { state: "awaiting_booking_prompt_response", data: {} };
          return;
        }
        if (["Scheduled", "Confirmed"].includes(appointment.status)) {
          const { data: patientRow2 } = await supabase.from('patients').select('messenger_id')
            .eq('id', appointment.patient_id).eq('clinic_id', clinicId).maybeSingle();
          if (!patientRow2?.messenger_id) {
            await supabase.from('appointments').update({ status: 'Confirmed' })
              .eq('id', appointment.id).eq('clinic_id', clinicId);
            if (req?.io) await emitAppointmentUpdate(req.io, clinicId, appointment.id);
            await sendMessage(sender_psid, "✅ Na-link na po ang inyong Messenger at nakumpirma na ang inyong appointment! Makakatanggap na kayo ng reminder bago ang inyong schedule. 🦷😊", pageAccessToken);
          } else {
            await sendMessage(sender_psid, "✅ Nakumpirma na po ang inyong appointment! Makakatanggap kayo ng reminder. Ingat po! 🦷", pageAccessToken);
          }
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        await sendMessage(sender_psid, "May nangyari po sa pagproseso ng inyong code. Pakicontact ang clinic para sa tulong. 😊", pageAccessToken);
        userStates[sender_psid] = { state: "default", data: {} };
        return;
      }

      case "awaiting_cancel_code": {
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        const code = message.trim();
        if (!/^\d+$/.test(code)) {
          await sendMessage(sender_psid, "Hmm, pakitype po ang inyong appointment code (numbers only). 😊", pageAccessToken);
          return;
        }
        const { data: apptData, error: apptErr } = await supabase
          .from('appointments').select('*, patient:patient_id (messenger_id)')
          .eq('id', code).eq('clinic_id', clinicId).maybeSingle();
        if (apptErr || !apptData) {
          await sendMessage(sender_psid, "Wala po kaming nahanap na appointment sa code na iyon. Type po ng 'Cancel' para lumabas, o 'Try Again' para subukan ulit.", pageAccessToken);
          userStates[sender_psid].state = "awaiting_cancel_code_retry";
          return;
        }
        const appointment = apptData;
        const isPatient = appointment.patient?.messenger_id === sender_psid;
        const isGuardian = appointment.guardian_messenger_id === sender_psid;
        if (!isPatient && !isGuardian) {
          await sendMessage(sender_psid, "Wala po kayong appointment sa code na iyan. Type po ng 'Cancel' para lumabas, o 'Try Again' para subukan ulit.", pageAccessToken);
          userStates[sender_psid].state = "awaiting_cancel_code_retry";
          return;
        }
        const apptDate = new Date(appointment.appointment_time);
        const now = new Date();
        now.setHours(0, 0, 0, 0);
        apptDate.setHours(0, 0, 0, 0);
        if (apptDate < now) {
          await sendMessage(sender_psid, "Hindi na po pwedeng i-cancel ang nakaraang appointment. Ang mga kasalukuyan at hinaharap na appointment lang po ang pwedeng i-cancel. 😊", pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        const msDiff = new Date(appointment.appointment_time).getTime() - new Date().getTime();
        if (msDiff <= 60 * 60 * 1000) {
          await sendMessage(sender_psid, "Pasensya na po, hindi na pwedeng i-cancel ang appointment na less than 1 hour na lang. Pakicontact na lang po ang clinic directly. 😊", pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        if (["Cancelled", "No Show"].includes(appointment.status)) {
          await sendMessage(sender_psid, "Na-cancel na po o minarkahan ng No Show ang appointment na ito. 😊", pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        await supabase.from('appointments').update({ status: 'Cancelled', reason: 'Cancelled via Messenger' })
          .eq('id', appointment.id).eq('clinic_id', clinicId);
        if (req?.io) await emitAppointmentUpdate(req.io, clinicId, appointment.id);
        await sendMessage(sender_psid, "Na-cancel na po ang inyong appointment. Kung kailangan ninyong mag-book ulit, message lang po kayo anytime. Ingat! 😊", pageAccessToken);
        userStates[sender_psid] = { state: "default", data: {} };
        return;
      }

      case "awaiting_cancel_code_retry": {
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        if (normalize(message) === "try again" || normalize(message) === "tryagain") {
          userStates[sender_psid].state = "awaiting_cancel_code";
          await sendMessage(sender_psid, "Sige po! Pakitype ulit ang inyong appointment code. 😊", pageAccessToken);
          return;
        }
        await sendMessage(sender_psid, "Type po ng 'Cancel' para lumabas, o 'Try Again' para subukan ulit. 😊", pageAccessToken);
        return;
      }

      case "awaiting_booking_prompt_response": {
        if (message === "DECLINE_BOOKING" || topIntent === 'no' || topIntent === 'cancel_flow') {
          const reply = aiReply || "Okay lang po! Kung kailangan ninyo ng appointment sa susunod, nandito lang kami. Ingat! 😊";
          await sendMessage(sender_psid, reply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        if (message === "BOOK_ANOTHER_APPOINTMENT" || topIntent === 'yes' || topIntent === 'book_appointment') {
          userStates[sender_psid] = { state: "awaiting_date", data: {} };
          const reply = aiReply || "Sige po! Pakitype ang inyong preferred na petsa sa format: YYYY-MM-DD 😊";
          await sendMessage(sender_psid, reply, pageAccessToken);
          return;
        }
        await sendMessage(sender_psid, "Gusto po ba ninyong mag-book ng bagong appointment? Sagutin lang po ng Yes o No. 😊", pageAccessToken);
        return;
      }

      case "awaiting_date": {
        // Cancel check
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
        if (!dateRegex.test(message.trim())) {
          const reply = aiReply || "Hmm, parang hindi tama ang format. Pakitype po sa format na YYYY-MM-DD, halimbawa: 2025-12-20. 😊";
          await sendMessage(sender_psid, reply, pageAccessToken);
          return;
        }
        if (!isClinicOpen(message.trim())) {
          const reply = aiReply || "Pasensya na po, sarado kami tuwing Linggo! 😊 Pwede po kayong pumili ng Lunes hanggang Sabado.";
          await sendMessage(sender_psid, reply, pageAccessToken);
          return;
        }
        const today = new Date(); today.setHours(0, 0, 0, 0);
        if (new Date(message.trim()) < today) {
          const reply = aiReply || "Ay, nakaraan na po ang petsang iyon! 😅 Pakitype ng petsa na hindi pa nakaraan.";
          await sendMessage(sender_psid, reply, pageAccessToken);
          return;
        }
        userState.data.date = message.trim();
        const patient = await findPatientByMessengerId(sender_psid, clinicId);
        if (patient) {
          const doubleBooked = await hasDoubleBookingOnDate(patient.id, userState.data.date, clinicId);
          if (doubleBooked) {
            userState.state = "awaiting_for_whom";
            await sendMessage(sender_psid, "Mukhang may appointment na kayo sa petsang iyon! 😊 Para kanino po ito — para sa inyo o para sa ibang tao?", pageAccessToken);
            await sendAppointmentForButtonTemplate(sender_psid, pageAccessToken);
            return;
          }
          userState.data.booking_for = "me";
          userState.data.patient_id = patient.id;
          userState.state = "awaiting_slot";
          const { slots, activeDentists } = await getAvailableSlots(userState.data.date, clinicId);
          userState.data.slots = slots;
          userState.data.activeDentists = activeDentists;
          if (!activeDentists.length) {
            await sendMessage(sender_psid, "Pasensya na po, wala pang available na dentist ngayon. Pakisubukan mamaya. 😊", pageAccessToken);
            userStates[sender_psid] = { state: "default", data: {} };
            return;
          }
          if (slots.length === 0) {
            await sendMessage(sender_psid, "Pasensya na po, puno na ang slots para sa araw na iyon. 😔 Pwede po kayong pumili ng ibang petsa?", pageAccessToken);
            userStates[sender_psid].state = "awaiting_date";
            userStates[sender_psid].data = {};
            return;
          }
          await sendMessage(sender_psid, "Narito po ang mga available na time slots para sa " + userState.data.date + ". Pumili lang po kayo! 😊", pageAccessToken);
          await sendTimeSlotButtonTemplate(sender_psid, userState.data.date, slots, pageAccessToken);
        } else {
          userState.data.booking_for = "me";
          userState.state = "awaiting_my_name";
          await sendMessage(sender_psid, "Pakitype lang po ang inyong buong pangalan para sa appointment. 😊", pageAccessToken);
        }
        return;
      }

      case "awaiting_my_name": {
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        userState.data.patient_name = toTitleCase(message.trim());
        userState.state = "awaiting_my_phone";
        await sendMessage(sender_psid, "Salamat po! May contact number po ba kayo? Pwede ring mag-type ng 'skip' kung ayaw ninyong ibigay. 📱", pageAccessToken);
        return;
      }

      case "awaiting_my_phone": {
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        let phone = null;
        if (normalize(message) !== "skip") {
          phone = message.trim();
          if (!/^\d{10,}$/.test(phone)) {
            await sendMessage(sender_psid, "Hmm, parang hindi tama ang format ng number. Numbers lang po, o mag-type ng 'skip'. 😊", pageAccessToken);
            return;
          }
        }
        userState.data.patient_phone = phone;
        const patient = await findPatientByNameAndPhone(userState.data.patient_name, phone, clinicId);
        if (patient) {
          userState.data.found_patient_id = patient.id;
          userState.data.found_patient_name = patient.name;
          userState.data.found_patient_phone = patient.phone;
          userState.state = "awaiting_my_confirm_match";
          let msg = `Nakakita kami ng existing record:\nPangalan: ${patient.name}\n`;
          if (patient.phone) msg += `Mobile: ${patient.phone}\n`;
          msg += "\nKayo po ba ito? I-reply ng YES para i-link ang inyong Messenger, o NO para gumawa ng bagong record. 😊";
          await sendMessage(sender_psid, msg, pageAccessToken);
        } else {
          userState.data.patient_id = null;
          userState.state = "awaiting_slot";
          const { slots, activeDentists } = await getAvailableSlots(userState.data.date, clinicId);
          userState.data.slots = slots;
          userState.data.activeDentists = activeDentists;
          if (!activeDentists.length) {
            await sendMessage(sender_psid, "Pasensya na po, wala pang available na dentist. Pakisubukan mamaya. 😊", pageAccessToken);
            userStates[sender_psid] = { state: "default", data: {} };
            return;
          }
          if (slots.length === 0) {
            await sendMessage(sender_psid, "Pasensya na po, puno na ang slots para sa araw na iyon. Pumili po ng ibang petsa. 😊", pageAccessToken);
            userStates[sender_psid].state = "awaiting_date";
            userStates[sender_psid].data = {};
          } else {
            await sendMessage(sender_psid, "Narito po ang mga available na slots! Pumili lang po. 😊", pageAccessToken);
            await sendTimeSlotButtonTemplate(sender_psid, userState.data.date, slots, pageAccessToken);
          }
        }
        return;
      }

      case "awaiting_my_confirm_match": {
        if (topIntent === 'yes') {
          await supabase.from('patients').update({ messenger_id: sender_psid })
            .eq('id', userState.data.found_patient_id).eq('clinic_id', clinicId);
          userState.data.patient_id = userState.data.found_patient_id;
          userState.state = "awaiting_slot";
          const { slots, activeDentists } = await getAvailableSlots(userState.data.date, clinicId);
          userState.data.slots = slots;
          userState.data.activeDentists = activeDentists;
          if (!activeDentists.length) {
            await sendMessage(sender_psid, "Pasensya na po, wala pang available na dentist. Pakisubukan mamaya. 😊", pageAccessToken);
            userStates[sender_psid] = { state: "default", data: {} };
            return;
          }
          if (slots.length === 0) {
            await sendMessage(sender_psid, "Puno na po ang slots para sa araw na iyon. Pumili po ng ibang petsa. 😊", pageAccessToken);
            userStates[sender_psid].state = "awaiting_date";
            userStates[sender_psid].data = {};
          } else {
            await sendMessage(sender_psid, "Na-link na po kayo! Narito ang mga available na slots. Pumili lang po! 😊", pageAccessToken);
            await sendTimeSlotButtonTemplate(sender_psid, userState.data.date, slots, pageAccessToken);
          }
        } else if (topIntent === 'no') {
          userState.data.patient_id = null;
          userState.state = "awaiting_slot";
          const { slots, activeDentists } = await getAvailableSlots(userState.data.date, clinicId);
          userState.data.slots = slots;
          userState.data.activeDentists = activeDentists;
          if (!activeDentists.length) {
            await sendMessage(sender_psid, "Pasensya na po, wala pang available na dentist. Pakisubukan mamaya. 😊", pageAccessToken);
            userStates[sender_psid] = { state: "default", data: {} };
            return;
          }
          if (slots.length === 0) {
            await sendMessage(sender_psid, "Puno na po ang slots para sa araw na iyon. Pumili po ng ibang petsa. 😊", pageAccessToken);
            userStates[sender_psid].state = "awaiting_date";
            userStates[sender_psid].data = {};
          } else {
            await sendMessage(sender_psid, "Sige po! Gawa na kami ng bagong record para sa inyo. Narito ang mga available na slots! 😊", pageAccessToken);
            await sendTimeSlotButtonTemplate(sender_psid, userState.data.date, slots, pageAccessToken);
          }
        } else {
          await sendMessage(sender_psid, "I-reply lang po ng YES o NO. 😊", pageAccessToken);
        }
        return;
      }

      case "awaiting_for_whom": {
        if (normalizedMsg === "1" || normalizedMsg === "for me" || normalizedMsg === "for_me") {
          await sendMessage(sender_psid, "Mayroon na po kayong appointment sa petsang iyon. Pakitype ng ibang petsa (YYYY-MM-DD). 😊", pageAccessToken);
          userStates[sender_psid].state = "awaiting_date";
          userStates[sender_psid].data = {};
          return;
        }
        if (normalizedMsg === "2" || normalizedMsg === "for someone else" || normalizedMsg === "for_someone_else") {
          userState.data.booking_for = "someone else";
          userState.state = "awaiting_patient_name";
          await sendMessage(sender_psid, "Pakitype po ang buong pangalan ng taong gusto ninyong i-book (halimbawa: inyong anak). 😊", pageAccessToken);
          return;
        }
        await sendAppointmentForButtonTemplate(sender_psid, pageAccessToken);
        return;
      }

      case "awaiting_patient_name": {
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        userState.data.patient_name = toTitleCase(message.trim());
        userState.state = "awaiting_patient_phone";
        await sendMessage(sender_psid, `Salamat po! May contact number po ba si ${userState.data.patient_name}? Pwede ring mag-type ng 'skip'. 📱`, pageAccessToken);
        return;
      }

      case "awaiting_patient_phone": {
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        let phone = null;
        if (normalize(message) !== "skip") {
          phone = message.trim();
          if (!/^\d{10,}$/.test(phone)) {
            await sendMessage(sender_psid, "Hindi tama ang format ng number. Numbers lang po, o mag-type ng 'skip'. 😊", pageAccessToken);
            return;
          }
        }
        userState.data.patient_phone = phone;
        const patient = await findPatientByNameAndPhone(userState.data.patient_name, phone, clinicId);
        if (patient) {
          const doubleBooked = await hasDoubleBookingOnDate(patient.id, userState.data.date, clinicId);
          if (doubleBooked) {
            await sendMessage(sender_psid, `Mayroon na pong appointment si ${userState.data.patient_name} sa ${userState.data.date}. Pakitype ng ibang petsa. 😊`, pageAccessToken);
            userStates[sender_psid].state = "awaiting_date";
            userStates[sender_psid].data = {};
            return;
          }
          userState.data.patient_id = patient.id;
        } else {
          userState.data.patient_id = null;
        }
        userState.state = "awaiting_slot";
        const { slots, activeDentists } = await getAvailableSlots(userState.data.date, clinicId);
        userState.data.slots = slots;
        userState.data.activeDentists = activeDentists;
        if (!activeDentists.length) {
          await sendMessage(sender_psid, "Pasensya na po, wala pang available na dentist. Pakisubukan mamaya. 😊", pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        if (slots.length === 0) {
          await sendMessage(sender_psid, "Puno na po ang slots para sa araw na iyon. Pumili po ng ibang petsa. 😊", pageAccessToken);
          userStates[sender_psid].state = "awaiting_date";
          userStates[sender_psid].data = {};
        } else {
          await sendMessage(sender_psid, "Narito po ang mga available na slots! Pumili lang po. 😊", pageAccessToken);
          await sendTimeSlotButtonTemplate(sender_psid, userState.data.date, slots, pageAccessToken);
        }
        return;
      }

      case "awaiting_slot": {
        if (topIntent === 'cancel_flow') {
          if (aiReply) await sendMessage(sender_psid, aiReply, pageAccessToken);
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }
        const availableSlots = userState.data.slots;
        let slot = null;
        if (normalizedMsg.startsWith("slot_")) {
          slot = message.substring(5);
        } else {
          const idx = parseInt(normalizedMsg, 10) - 1;
          if (!availableSlots || isNaN(idx) || idx < 0 || idx >= availableSlots.length) {
            await sendMessage(sender_psid, "Pakitap lang po ang isa sa mga button para pumili ng time slot. 😊", pageAccessToken);
            return;
          }
          slot = availableSlots[idx];
        }
        if (!availableSlots.includes(slot)) {
          await sendMessage(sender_psid, "Hindi valid ang piniling slot. Pakipili ng isa pa. 😊", pageAccessToken);
          return;
        }
        userState.data.slot = slot;
        userState.state = "confirming";
        let summary = `📋 Booking Summary:\n📅 Petsa: ${userState.data.date}\n⏰ Oras: ${slot}\n`;
        if (userState.data.booking_for === "me") {
          const patient = await findPatientByMessengerId(sender_psid, clinicId);
          summary += `👤 Pangalan: ${patient ? patient.name : userState.data.patient_name}\n`;
          if (patient?.phone) summary += `📱 Mobile: ${patient.phone}\n`;
          else if (userState.data.patient_phone) summary += `📱 Mobile: ${userState.data.patient_phone}\n`;
        } else {
          summary += `👤 Pangalan: ${userState.data.patient_name}\n`;
          if (userState.data.patient_phone) summary += `📱 Mobile: ${userState.data.patient_phone}\n`;
        }
        summary += "\nTama po ba ito? I-confirm o i-cancel lang po. 😊";
        await sendConfirmationButtonTemplate(sender_psid, summary, pageAccessToken);
        return;
      }

      case "confirming": {
        const slot24 = to24HourFormat(userState.data.slot);
        const datetime = `${userState.data.date}T${slot24}:00+08:00`;
        const activeDentists = userState.data.activeDentists;
        let assignedDentist = null;

        for (const dentist of activeDentists) {
          const dayOfWeek = new Date(userState.data.date).getDay();
          const { data: blocks } = await supabase.from('dentist_availability')
            .select('start_time,end_time,is_available').eq('dentist_id', dentist.id)
            .or(`specific_date.eq.${userState.data.date},day_of_week.eq.${dayOfWeek}`)
            .eq('is_available', false).eq('clinic_id', clinicId);
          let isBlocked = false;
          for (const block of (blocks || [])) {
            const [sh, sm] = block.start_time.split(':').map(Number);
            const [eh, em] = block.end_time.split(':').map(Number);
            const [h, m] = slot24.split(':').map(Number);
            const slotMin = h * 60 + m;
            if (slotMin >= sh * 60 + sm && slotMin < eh * 60 + em) { isBlocked = true; break; }
          }
          if (isBlocked) continue;
          const { data: bookings } = await supabase.from('appointments').select('id,status')
            .eq('dentist_id', dentist.id).eq('appointment_time', datetime).eq('clinic_id', clinicId);
          if ((bookings || []).some(b => b.status !== 'Cancelled')) continue;
          assignedDentist = dentist;
          break;
        }

        if (!assignedDentist) {
          await sendMessage(sender_psid, "Pasensya na po, walang available na dentist para sa slot na iyon. Pakisubukan ng ibang slot. 😊", pageAccessToken);
          userStates[sender_psid].state = "awaiting_slot";
          return;
        }

        let patient_id = userState.data.patient_id;
        if (!patient_id) {
          const insertPayload = {
            name: String(userState.data.patient_name),
            phone: userState.data.patient_phone || null,
            clinic_id: clinicId
          };
          if (userState.data.booking_for === "me") insertPayload.messenger_id = sender_psid;
          const { data: insertedPatient, error: insErr } = await supabase.from('patients')
            .insert(insertPayload).select().single();
          if (insErr) {
            console.error("Error inserting patient:", insErr);
            await sendMessage(sender_psid, "May nangyari po sa pagproseso. Pakisubukan ulit. 😊", pageAccessToken);
            userStates[sender_psid] = { state: "default", data: {} };
            return;
          }
          patient_id = insertedPatient.id;
        }

        const { data: existingAppointments } = await supabase.from('appointments').select('id,status')
          .eq('dentist_id', assignedDentist.id).eq('appointment_time', datetime).eq('clinic_id', clinicId);

        // Cancel booking
        if (topIntent === 'cancel_flow' || normalizedMsg === 'cancel_booking') {
          let targetId = null;
          try {
            if (existingAppointments?.length > 0) {
              targetId = existingAppointments[0].id;
              await supabase.from('appointments').update({ status: 'Cancelled', reason: 'Messenger Booking', guardian_messenger_id: sender_psid })
                .eq('id', targetId).eq('clinic_id', clinicId);
            } else {
              const { data: ins } = await supabase.from('appointments').insert({
                dentist_id: assignedDentist.id, patient_id, appointment_time: datetime,
                booking_origin: 'Messenger Booking', status: 'Cancelled', reason: 'Messenger Booking',
                guardian_messenger_id: sender_psid, clinic_id: clinicId
              }).select('id').single();
              if (ins) targetId = ins.id;
            }
          } catch (err) { console.error("Error saving cancelled:", err); }
          if (req?.io && targetId) await emitAppointmentUpdate(req.io, clinicId, targetId);
          const reply = aiReply || "Na-cancel po ang inyong booking. Kung gusto ninyong mag-book ulit, sabihin lang po! 😊";
          await sendMessage(sender_psid, reply, pageAccessToken);
          justCancelled[sender_psid] = true;
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }

        // Confirm booking
        if (topIntent === 'yes' || normalizedMsg === 'confirm_booking' || ['ok', 'confirm'].includes(normalizedMsg)) {
          let appointmentId;
          try {
            if (existingAppointments?.length > 0) {
              const existingId = existingAppointments[0].id;
              const { data: updated, error: updErr } = await supabase.from('appointments')
                .update({ patient_id, status: 'Confirmed', reason: 'Messenger Booking', guardian_messenger_id: sender_psid })
                .eq('id', existingId).eq('clinic_id', clinicId).select('id').single();
              appointmentId = updErr ? existingId : updated.id;
            } else {
              const { data: ins } = await supabase.from('appointments').insert({
                dentist_id: assignedDentist.id, patient_id, appointment_time: datetime,
                booking_origin: 'Messenger Booking', status: 'Confirmed', reason: 'Messenger Booking',
                guardian_messenger_id: sender_psid, clinic_id: clinicId
              }).select('id').single();
              if (ins) appointmentId = ins.id;
            }

            let bookedName = userState.data.patient_name;
            if (appointmentId) {
              const { data: apptDetail } = await supabase.from('appointments')
                .select('id, patient_id, dentist_id').eq('id', appointmentId).eq('clinic_id', clinicId).maybeSingle();
              if (apptDetail) {
                const { data: p } = await supabase.from('patients').select('name, phone')
                  .eq('id', apptDetail.patient_id).eq('clinic_id', clinicId).maybeSingle();
                if (p) bookedName = p.name;
              }
            }

            if (req?.io && appointmentId) await emitAppointmentUpdate(req.io, clinicId, appointmentId);

            await sendMessage(sender_psid,
              `✅ Na-book na po ang inyong appointment!\n\n📅 Petsa: ${userState.data.date}\n⏰ Oras: ${userState.data.slot}\n👤 Pangalan: ${bookedName}\n🔖 Appointment Code: ${appointmentId || ''}\n\nSalamat po sa pagpili ng Palo Dentcare! Ingat at God bless! 🦷😊`,
              pageAccessToken
            );
          } catch (err) {
            console.error("Error booking:", err);
            await sendMessage(sender_psid, "May nangyari po sa pag-book. Pakisubukan ulit. 😊", pageAccessToken);
          }
          userStates[sender_psid] = { state: "default", data: {} };
          return;
        }

        await sendMessage(sender_psid, "Pakitap lang po ang Confirm o Cancel button para matuloy. 😊", pageAccessToken);
        return;
      }

      default: {
        await sendMessage(sender_psid, "Pasensya na po, may nangyari. Magsimula ulit tayo. I-type lang po ang 'appointment' o 'book' para magsimula. 😊", pageAccessToken);
        userStates[sender_psid] = { state: "default", data: {} };
        return;
      }
    }
  } catch (err) {
    console.error('❌ Error in handleMessage:', err);
    await sendMessage(sender_psid, "Sorry po, may nangyari. Pakisubukan ulit. 😊", pageAccessToken);
    userStates[sender_psid] = { state: "default", data: {} };
  }
}

module.exports = { router, sendMessage };