export const TIME_ZONES = [
  // Philippines and East Asia
  { value: "Asia/Manila", label: "Asia/Manila (Philippines)" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo (Japan)" },
  { value: "Asia/Kuala_Lumpur", label: "Asia/Kuala_Lumpur (Malaysia)" },
  { value: "Asia/Seoul", label: "Asia/Seoul (South Korea)" },
  { value: "Asia/Bangkok", label: "Asia/Bangkok (Thailand)" },
  { value: "Asia/Vientiane", label: "Asia/Vientiane (Laos)" },
  { value: "Asia/Yangon", label: "Asia/Yangon (Myanmar)" },
  { value: "Asia/Jakarta", label: "Asia/Jakarta (Indonesia, Western Time)" },
  { value: "Asia/Makassar", label: "Asia/Makassar (Indonesia, Central Time)" },
  { value: "Asia/Jayapura", label: "Asia/Jayapura (Indonesia, Eastern Time)" },
  { value: "Asia/Dubai", label: "Asia/Dubai (UAE)" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata (India)" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai (China)" },
  // Middle East & South Asia
  { value: "Asia/Riyadh", label: "Asia/Riyadh (Saudi Arabia)" },
  { value: "Asia/Karachi", label: "Asia/Karachi (Pakistan)" },
  { value: "Asia/Dhaka", label: "Asia/Dhaka (Bangladesh)" },
  // Oceania & Pacific
  { value: "Australia/Sydney", label: "Australia/Sydney (Australia)" },
  { value: "Pacific/Midway", label: "Pacific/Midway (UTC-11:00)" },
  { value: "Pacific/Honolulu", label: "Pacific/Honolulu (Hawaii, US)" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland (New Zealand)" },
  // Americas
  { value: "America/Adak", label: "America/Adak (Alaska, US)" },
  { value: "America/Anchorage", label: "America/Anchorage (Alaska, US)" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles (Pacific US)" },
  { value: "America/Denver", label: "America/Denver (Mountain US)" },
  { value: "America/Chicago", label: "America/Chicago (Central US)" },
  { value: "America/New_York", label: "America/New_York (Eastern US)" },
  { value: "America/Toronto", label: "America/Toronto (Canada)" },
  { value: "America/Mexico_City", label: "America/Mexico_City (Mexico)" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo (Brazil)" },
  { value: "America/Buenos_Aires", label: "America/Buenos_Aires (Argentina)" },
  // Europe
  { value: "Europe/London", label: "Europe/London (UK)" },
  { value: "Europe/Berlin", label: "Europe/Berlin (Germany)" },
  { value: "Europe/Paris", label: "Europe/Paris (France)" },
  { value: "Europe/Istanbul", label: "Europe/Istanbul (Turkey)" },
  { value: "Europe/Moscow", label: "Europe/Moscow (Russia)" },
  // Africa
  { value: "Africa/Cairo", label: "Africa/Cairo (Egypt)" },
  { value: "Africa/Nairobi", label: "Africa/Nairobi (Kenya)" },
  { value: "Africa/Lagos", label: "Africa/Lagos (Nigeria)" },
];